"""empty message

Revision ID: 5138a186f5bd
Revises: 9c80c71187b4
Create Date: 2018-05-14 14:56:52.122761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5138a186f5bd'
down_revision = '9c80c71187b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderGood',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['good.id'], )
    )
    op.drop_constraint('good_ibfk_2', 'good', type_='foreignkey')
    op.drop_column('good', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('good_ibfk_2', 'good', 'order', ['order_id'], ['id'])
    op.drop_table('OrderGood')
    # ### end Alembic commands ###
