"""empty message

Revision ID: 6579ca591c76
Revises: 969457d2bff3
Create Date: 2018-05-08 13:19:45.622664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6579ca591c76'
down_revision = '969457d2bff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('good', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'good', 'order', ['order_id'], ['id'])
    op.add_column('user', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'order_id')
    op.drop_constraint(None, 'good', type_='foreignkey')
    op.drop_column('good', 'order_id')
    op.drop_table('order')
    # ### end Alembic commands ###
