"""empty message

Revision ID: 969457d2bff3
Revises: 93760d04a675
Create Date: 2018-05-06 01:24:46.173585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969457d2bff3'
down_revision = '93760d04a675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    # ### end Alembic commands ###
