"""empty message

Revision ID: 9c80c71187b4
Revises: e20b854ff04b
Create Date: 2018-05-11 14:05:51.884084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c80c71187b4'
down_revision = 'e20b854ff04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('good', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'good', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'good', type_='foreignkey')
    op.drop_column('good', 'order_id')
    op.drop_table('order')
    # ### end Alembic commands ###
